source 'https://rubygems.org'

# Rails
gem 'rails', '4.2.4'
gem 'rails-api'

gem 'spring', :group => :development

# Databases
gem 'sqlite3', :group => :development

# Authentication
gem 'devise'
gem 'devise_token_auth'
gem 'omniauth'
gem 'omniauth-google-oauth2'
gem 'signet'

# Authorization
gem 'cancancan'
gem 'paper_trail', '~> 4.0.0'

# CORS
gem 'rack-cors', :require => 'rack/cors'

# Nokogiri
gem 'nokogiri'

# Paperclip & Fog
gem 'paperclip'
gem 'fog'

# IMS LTI
gem 'ims-lti'

# To use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
